### ISSUE TITLE
Copy All Playlists does not work

### ISSUE THREAD

**Issue by stepheniscool** [linsomniac/spotify_to_ytmusic#111]
Running on a mac

I can login to YT Music. 

I can login to Spotify backup.

I was able to load all of the liked songs and copy over to YT music.

When I try to copy all of my playlists, it doesnt work. It stops after the first playlist is created in YT music. So I ran the line in terminal and now I see the error but do not know what to do:

..........................................................................................................................................................
MacBook-Pro ~ % s2yt_copy_all_playlists
Looking up playlist '2024 new songs': id=PLJlJ7Mga717ImQmeSs0dmdGcqTfW-eHfc
== Youtube Playlist: 2024 new songs
== Spotify Playlist: 2024 new songs
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/s2yt_copy_all_playlists", line 8, in <module>
    sys.exit(copy_all_playlists())
             ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify2ytmusic/cli.py", line 321, in copy_all_playlists
    backend.copy_all_playlists(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify2ytmusic/backend.py", line 526, in copy_all_playlists
    copier(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify2ytmusic/backend.py", line 379, in copier
    for src_track in src_tracks:
                     ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/spotify2ytmusic/backend.py", line 160, in iter_spotify_playlist
    if src_track["track"] is None:
       ~~~~~~~~~^^^^^^^^^
**TypeError: string indices must be integers, not 'str'**

**Comment by nerdicly** [comment]
Same issues.
