### ISSUE TITLE
s2yt_load_liked and s2yt_copy_all_playlists not working

### ISSUE THREAD

**Issue by CloudRunnerRex** [linsomniac/spotify_to_ytmusic#151]
I am about to lose my mind. I have been up all night, and from not being able to install pip, to having to figure out Google's API and finding the fact taht the API needs to be TV, to having the playlist json not generating in the right location, to having to fix the backup .py file with the new code because of Spotify's new API updates, to having to uninstall and reinstall everything because of a custom install location, I give up now. **_I try run load liked and get this result:_** 

C:\Users\ashe4>s2yt_load_liked
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Scripts\s2yt_load_liked.exe\__main__.py", line 7, in <module>
    sys.exit(load_liked())
             ~~~~~~~~~~^^
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\cli.py", line 199, in load_liked
    backend.copier(
    ~~~~~~~~~~~~~~^
        backend.iter_spotify_playlist(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        args.algo,
        ^^^^^^^^^^
    )
    ^
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\backend.py", line 379, in copier
    for src_track in src_tracks:
                     ^^^^^^^^^^
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\backend.py", line 150, in iter_spotify_playlist
    src_pl = find_spotify_playlist(spotify_pls, src_pl_id)
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\backend.py", line 148, in find_spotify_playlist
    raise ValueError(f"Could not find Spotify playlist {src_pl_id}")
ValueError: Could not find Spotify playlist None

**_and when i try to run copy all playlists I get this:_**

C:\Users\ashe4>s2yt_copy_all_playlists
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Scripts\s2yt_copy_all_playlists.exe\__main__.py", line 7, in <module>
    sys.exit(copy_all_playlists())
             ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\cli.py", line 321, in copy_all_playlists
    backend.copy_all_playlists(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        track_sleep=args.track_sleep,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        privacy_status=args.privacy,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\backend.py", line 513, in copy_all_playlists
    dst_pl_id = get_playlist_id_by_name(yt, pl_name)
  File "C:\Users\ashe4\AppData\Local\Programs\Python\Python313\Lib\site-packages\spotify2ytmusic\backend.py", line 190, in get_playlist_id_by_name
    playlists = yt.get_library_playlists(limit=5000)
  File "C:\Users\ashe4\AppData\Roaming\Python\Python313\site-packages\ytmusicapi\mixins\library.py", line 33, in get_library_playlists
    response = self._send_request(endpoint, body)
  File "C:\Users\ashe4\AppData\Roaming\Python\Python313\site-packages\ytmusicapi\ytmusic.py", line 278, in _send_request
    raise YTMusicServerError(message + error)
ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.

I am on verge of tears, and literally made a github account jsut to post for help. I beg.

**Comment by CloudRunnerRex** [comment]
![Screenshot 2024-12-29 014409](https://github.com/user-attachments/assets/381aaced-a7a5-4dbe-8ea8-d818f7a1e477)
![image](https://github.com/user-attachments/assets/242a8983-6429-48f2-bba8-ba49726ac127)

**Comment by roopeshshettyb** [comment]
It's because of the login method being changed in the package.

Refer to #132 & #150 

So basically now, 

You have to

1. Copy the headers from youtube music - This [doc](https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html) gives you instructions.
2. Type  `pbpaste | ytmusicapi browser` in your cli and press enter
3. You should be logged in now.

**Comment by CloudRunnerRex** [comment]
Hello! Was able to follow the doc instructions and not get a erroer message, so I assume the ytmusicapi browser function worked. But when I do the pbpaste comamnd you mentioned, nothing happens. 
<img width="815" alt="image" src="https://github.com/user-attachments/assets/76344ad5-a361-4c10-b11d-f445120b2dfe" />

**Comment by CloudRunnerRex** [comment]
Never mind, I switched to Powershell, and I renamed the file to "oauth.json" and it started running fine. Thank you!

**Comment by Whatever57** [comment]
> Never mind, I switched to Powershell, and I renamed the file to "oauth.json" and it started running fine. Thank you!

I am stuck as well on the same damn page, do you mind guiding me on 2 things?
1. How do you fix the playlist json problem and
2. How did you rename the file to "oauth.json"

I have already done things like the Google API and changing the backup .py
![image_2025-01-08_002331288](https://github.com/user-attachments/assets/f8b4f3d5-9e34-4751-94f0-bfc74176f86a)
Still I am here

**Comment by flyercarol** [comment]
You don't have to include pbpaste there.
1. Make sure you have ytmusicapi python lib installed at your python environment.
2. Next in your powershell/cmd, navigate to **the folder** you want the browser.json to be downloaded.
3. Run `ytmusicapi browser`
4. Follow the instructions, i.e. paste your request headers (from Accept */* till end) into terminal, press Ctrl+Z, press Enter
5. browser.json should appear in **that** folder
6. Rename **browser.json** to **oauth.json**
7. You should now be able to log in to your yt music
