### ISSUE TITLE
Liked songs won't load and list playlists wont list

### ISSUE THREAD

**Issue by LaKinguin** [linsomniac/spotify_to_ytmusic#71]
After I press back up and it finishes, I go to press Load on the "Load liked songs" tab but it just makes a blank line. The same goes for List playlists and Copy all playlists. They all do nothing

**Comment by LaKinguin** [comment]
I found the root of the problem but I still can't fix it. The problem was I didn't have playlists.json but everytime I try to back up I get this error code. Exception in thread Thread-3 (main):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\spotify2ytmusic\spotify_backup.py", line 179, in main
    with open(file, "w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'playlists.json'
