### ISSUE TITLE
s2yt_copy_playlist Exception: Server returned HTTP 404: Not Found.

### ISSUE THREAD

**Issue by Schurkee** [linsomniac/spotify_to_ytmusic#9]
When I enter s2yt_copy_playlist i get these errors:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Schurkee\AppData\Local\Programs\Python\Python312\Scripts\s2yt_copy_playlist.exe\__main__.py", line 7, in <module>
  File "C:\Users\Schurkee\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify2ytmusic\cli.py", line 153, in copy_playlist
    copier(src_pl_id, dst_pl_id, args.dry_run, args.track_sleep)
  File "C:\Users\Schurkee\AppData\Local\Programs\Python\Python312\Lib\site-packages\spotify2ytmusic\cli.py", line 166, in copier
    yt_pl = yt.get_playlist(playlistId=dst_pl_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Schurkee\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\mixins\playlists.py", line 108, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Schurkee\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\ytmusic.py", line 238, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.
```

**Comment by linsomniac** [comment]
It looks like that is failing to get the YTMusic playlist, could there be a typo in the playlist ID?  It should be a string like "PL_cdsahjkFHJcdhjakcdSJKHEhjfa83HJfd".  The command would be something like `s2yt_copy_playlist --dry-run 2UosVEKxgCdwqwSQXZOwYx PL_2Ovmm8JEYSSvK3c3JBun13q2lXtzfqO`

I've added some code to make this error more clear.

**Comment by Schurkee** [comment]
> It looks like that is failing to get the YTMusic playlist, could there be a typo in the playlist ID? It should be a string like "PL_cdsahjkFHJcdhjakcdSJKHEhjfa83HJfd". The command would be something like `s2yt_copy_playlist --dry-run 2UosVEKxgCdwqwSQXZOwYx PL_2Ovmm8JEYSSvK3c3JBun13q2lXtzfqO`
> 
> I've added some code to make this error more clear.

oh it's my fault I didn't now I had to copy that I thought I just need the actual name thank you :)

**Comment by linsomniac** [comment]
There's a new version I'm pushing up now which allows you to copy by name, if you specify "+" before the name: `s2yt_copy_playlist <SPOTIFY_ID> "+My Playlist Name"`

It also adds a `s2yt_copy_all_playlists" that copies everything except liked by name.
